# Bot Token
token: "NjMzNzI2MzcxMTM4NTAyNjg1.Xe0MkA.8Wi-dFFNV5UoHg25zL3L00mFxlQ"
# Bot Language
language: "de"
# Discord Server
guild: 621724759645749258
# Admin Role
role: 'Rosengarde'


# Game Instructor
arma3: 245319138380087296
backup: 210478067800342530


#DB
host: "localhost"
user: "root"
passwd: "Zaubertrick.-98"
database: "testDB"
